sudo: required
services:
 - docker 

before_install:
 - docker build -t jonathanzea/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true jonathanzea/docker-react npm run test -- --coverage

deploy:
 provider: elasticbeanstalk
 region: "eu-west-1"
 app: "docker-react"
 env: "DockerReact-env" 
 bucket_name: "elasticbeanstalk-eu-west-1-219942322862" 
 bucket_path: "docker-react"
 on:
  branch: master
 access_key_id: $AWS_ACESS_KEY
 secret_access_key:
  secure: "$AWS_SECRET_KEY"