version: '3'
services:
 
 frontend:
  build:
   context: .
   dockerfile: Dockerfile.dev
  ports: 
   - "8090:3000"
  volumes:
   - /app/node_modules
   - .:/app
 
 frontend-test:
  build:
   context: .
   dockerfile: Dockerfile.dev
  volumes:
   - /app/node_modules
   - .:/app
  command: ["npm","run","test"]